env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
types:
  - jest
rules: 
  semi: 
    - warn 
    - never
  comma-dangle: 
    - error
    - never

